language: python
python: "3.6"      # current default Python on Travis CI
# command to install dependencies
install: pip install -r requirements.txt

services : postgresql

<<<<<<< HEAD
env: DJANGO_SETTINGS_MODULE="disquaire_project.settings.travis"
=======
env: DJANGO_SETTINGS_MODULE=disquaire_project.settings.travis
>>>>>>> c78b77dae63a6936775e442351001e9627356fde

# command to run tests
script: ./manage.py test homepage
