# Generated by Django 3.0.4 on 2020-04-24 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=100)),
                ('keywords', models.CharField(default='DEFAULT VALUE', max_length=250)),
                ('brand', models.CharField(max_length=100)),
                ('nutriscore', models.CharField(max_length=1)),
                ('fat_value', models.CharField(default='DEFAULT VALUE', max_length=100)),
                ('saturated_value', models.CharField(default='DEFAULT VALUE', max_length=100)),
                ('salt_value', models.CharField(default='DEFAULT VALUE', max_length=100)),
                ('sugars_value', models.CharField(default='DEFAULT VALUE', max_length=100)),
                ('fat_level', models.CharField(default='DEFAULT VALUE', max_length=100)),
                ('saturated_level', models.CharField(default='DEFAULT VALUE', max_length=100)),
                ('salt_level', models.CharField(default='DEFAULT VALUE', max_length=100)),
                ('sugars_level', models.CharField(default='DEFAULT VALUE', max_length=100)),
                ('stores', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('image', models.CharField(default='DEFAULT VALUE', max_length=200)),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Favoris',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='homepage.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
