# Generated by Django 3.0.4 on 2020-04-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='keywords',
            field=models.CharField(default='DEFAULT VALUE', max_length=200),
        ),
    ]
