# Generated by Django 3.0.4 on 2020-04-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20200424_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(default='DEFAULT VALUE', max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='stores',
            field=models.CharField(max_length=250),
        ),
    ]
