# Generated by Django 3.0.4 on 2020-04-28 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20200424_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoris',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Product'),
        ),
        migrations.AddConstraint(
            model_name='favoris',
            constraint=models.UniqueConstraint(fields=('product_id', 'user'), name='uniqueFavoris'),
        ),
    ]
